import os
import re
from datetime import datetime
from fpdf import FPDF
from pydub import AudioSegment

# CONFIG

SAVED_STORIES_DIR = "saved_stories"
os.makedirs(SAVED_STORIES_DIR, exist_ok=True)

# Hindi font path — download free Devanagari font
HINDI_FONT_PATH = "backend/features/fonts/NotoSansDevanagari-Regular.ttf"
FONT_DIR        = "backend/features/fonts"
os.makedirs(FONT_DIR, exist_ok=True)

# DOWNLOAD HINDI FONT IF MISSING

def download_hindi_font():
    if os.path.exists(HINDI_FONT_PATH):
        return True

    print(" Downloading Hindi font for PDF...")
    try:
        import urllib.request
        font_url = (
            "https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/"
            "NotoSansDevanagari/NotoSansDevanagari-Regular.ttf"
        )
        urllib.request.urlretrieve(font_url, HINDI_FONT_PATH)
        print(f" Hindi font downloaded → {HINDI_FONT_PATH}")
        return True
    except Exception as e:
        print(f"  Font download failed: {e}")
        print("   Hindi PDF will use basic formatting")
        return False

# CREATE STORY FOLDER

def create_story_folder(story_id, language, category):
    timestamp  = datetime.now().strftime("%Y%m%d_%H%M%S")
    folder_name= f"story_{story_id}_{language}_{category}_{timestamp}"
    folder_path= os.path.join(SAVED_STORIES_DIR, folder_name)
    os.makedirs(folder_path, exist_ok=True)
    return folder_path

# SAVE STORY AS TXT

def save_as_txt(story_text, prompt, language, category, folder_path, story_id):
    txt_path = os.path.join(folder_path, f"story_{story_id}.txt")

    category_str = category.replace("_", " ").title()
    timestamp    = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lang_str     = "Hindi 🇮🇳" if language == "hindi" else "English 🇬🇧"

    content = f"""{'='*60}
HORROR STORY #{story_id}
{'='*60}
Language  : {lang_str}
Category  : {category_str}
Generated : {timestamp}
Prompt    : {prompt}
{'='*60}

{story_text}

{'='*60}
Generated by Horror Story Generator
{'='*60}
"""

    with open(txt_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"   TXT saved  → {txt_path}")
    return txt_path

# SAVE STORY AS PDF

def save_as_pdf(story_text, prompt, language, category, folder_path, story_id):
    pdf_path     = os.path.join(folder_path, f"story_{story_id}.pdf")
    category_str = category.replace("_", " ").title()
    timestamp    = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    try:
        pdf = FPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)

        # Add Hindi font if available
        hindi_font_available = False
        if language == "hindi" and download_hindi_font():
            try:
                pdf.add_font("NotoDevanagari", "", HINDI_FONT_PATH, uni=True)
                hindi_font_available = True
            except:
                pass

        # ── Header ──
        if hindi_font_available:
            pdf.set_font("NotoDevanagari", size=20)
        else:
            pdf.set_font("Helvetica", "B", size=20)

        pdf.set_text_color(150, 0, 0)   # dark red
        pdf.cell(0, 12, "HORROR STORY", ln=True, align="C")
        pdf.ln(4)

        # ── Divider ──
        pdf.set_draw_color(150, 0, 0)
        pdf.set_line_width(0.8)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(6)

        # ── Metadata ──
        pdf.set_text_color(80, 80, 80)
        if hindi_font_available:
            pdf.set_font("NotoDevanagari", size=10)
        else:
            pdf.set_font("Helvetica", size=10)

        lang_str = "Hindi" if language == "hindi" else "English"
        pdf.cell(0, 7, f"Language: {lang_str}    Category: {category_str}    Date: {timestamp}", ln=True)
        pdf.ln(2)
        pdf.cell(0, 7, f"Prompt: {prompt[:80]}", ln=True)
        pdf.ln(4)

        # ── Divider ──
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(8)

        # ── Story text ──
        pdf.set_text_color(20, 20, 20)
        if hindi_font_available:
            pdf.set_font("NotoDevanagari", size=12)
        else:
            pdf.set_font("Helvetica", size=12)

        # Split into paragraphs
        paragraphs = story_text.strip().split("\n\n")
        for para in paragraphs:
            para = para.strip()
            if not para:
                continue

            # Detect dialogue for styling
            if '"' in para or '\u201c' in para or '\u201d' in para:
                pdf.set_text_color(100, 0, 0)   # dark red for dialogue
                pdf.set_font("Helvetica", "I", size=12) if not hindi_font_available else None
            else:
                pdf.set_text_color(20, 20, 20)
                if not hindi_font_available:
                    pdf.set_font("Helvetica", size=12)

            pdf.multi_cell(0, 8, para)
            pdf.ln(4)

        # ── Footer ──
        pdf.set_y(-20)
        pdf.set_font("Helvetica", "I", size=9)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 10, "Generated by Horror Story Generator", align="C")

        pdf.output(pdf_path)
        print(f"   PDF saved  → {pdf_path}")
        return pdf_path

    except Exception as e:
        print(f"    PDF error: {e}")
        return None

# SAVE AUDIO

def save_audio(audio_path, folder_path, story_id):
    if not audio_path or not os.path.exists(audio_path):
        print("    No audio to save")
        return None

    dest_path = os.path.join(folder_path, f"story_{story_id}_audio.mp3")

    try:
        # Convert to mp3 if needed
        if audio_path.endswith(".wav"):
            audio = AudioSegment.from_wav(audio_path)
            audio.export(dest_path, format="mp3", bitrate="192k")
        else:
            import shutil
            shutil.copy2(audio_path, dest_path)

        size = os.path.getsize(dest_path) / 1024
        print(f"   MP3 saved  → {dest_path} ({size:.1f} KB)")
        return dest_path

    except Exception as e:
        print(f"    Audio save error: {e}")
        return None

# SAVE EVERYTHING TOGETHER

def save_complete_story(
    story_text, prompt, language, category,
    audio_path=None, story_id="001"
):
    print("\n" + "="*60)
    print(" SAVING COMPLETE STORY")
    print("="*60)

    # Create story folder
    folder_path = create_story_folder(story_id, language, category)
    print(f"   Folder: {folder_path}\n")

    results = {}

    # Save TXT
    txt_path = save_as_txt(
        story_text, prompt, language,
        category, folder_path, story_id
    )
    results["txt"] = txt_path

    # Save PDF
    pdf_path = save_as_pdf(
        story_text, prompt, language,
        category, folder_path, story_id
    )
    results["pdf"] = pdf_path

    # Save Audio
    if audio_path:
        mp3_path = save_audio(audio_path, folder_path, story_id)
        results["mp3"] = mp3_path

    # Summary
    print("\n" + "="*60)
    print(" STORY SAVED SUCCESSFULLY!")
    print("="*60)
    print(f"   Location : {folder_path}")
    if results.get("txt"):
        print(f"   TXT file : story_{story_id}.txt")
    if results.get("pdf"):
        print(f"   PDF file : story_{story_id}.pdf")
    if results.get("mp3"):
        print(f"   MP3 file : story_{story_id}_audio.mp3")
    print("="*60 + "\n")

    return folder_path, results

# MAIN — for testing

if __name__ == "__main__":
    test_story = """रात के अंधेरे में राहुल उस पुरानी हवेली के पास पहुँचा।

दरवाज़ा अपने आप खुल गया।

"अंदर आ जाओ बेटा।" एक बूढ़ी आवाज़ आई।

राहुल काँप गया। उसने पूछा "कौन हो तुम?"

पर असली सच्चाई तो ये थी।

वो आवाज़ उसकी दादी की थी। जो तीन साल पहले मर चुकी थीं।"""

    save_complete_story(
        story_text = test_story,
        prompt     = "एक भूतिया हवेली की कहानी",
        language   = "hindi",
        category   = "haunted_house",
        audio_path = None,
        story_id   = "001"
    )